before_build:
 - nuget restore
configuration: Release
build:
    publish_nuget: true
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:".\UnitLibraryTests\bin\Release\UnitLibraryTests.dll" -filter:"+[UnitClassLibrary*]* -[UnitLibraryTests*]*" -output:UnitClassLibrary_coverage.xml
after_test:
 - .\packages\Codecov.1.0.1\tools\codecov.exe -f ".\UnitClassLibrary_coverage.xml" -t ee21fa3e-c115-4d82-878e-c4e587a03c0d
deploy:
    provider: NuGet
    api_key: b11f3056-8100-4e18-bc0a-2dd2193f1e90
    on:
        branch: master