before_build:
 - nuget restore
configuration: Release
build:
    project: UnitClassLibrary.sln
    publish_nuget: true
test_script:
 - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\NUnit.ConsoleRunner.3.7.0\tools\nunit3-console.exe" -targetargs:".\UnitLibraryTests\bin\Release\UnitLibraryTests.dll" -filter:"+[UnitClassLibrary*]* -[UnitLibraryTests*]*" -output:UnitClassLibrary_coverage.xml
environment:
  CODECOV_REPO_TOKEN:
    secure: oBDB8d7yJ9NcvW5QkC7INOSrkD+sX8Xi9C+8BeagA7T+7a1PLBsp6sgVbuMk0ICw
  COVERALLS_REPO_TOKEN:
    secure: 6gu2J7jMuGpXIRw4OZR3v8qs0/fHwPGxs1rR3dZu5Mh5M2Tab+POlE38m09vLS+P
after_test:
 - .\packages\Codecov.1.0.2\tools\codecov.exe -f ".\UnitClassLibrary_coverage.xml" -t %CODECOV_REPO_TOKEN%
 - .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover .\UnitClassLibrary_coverage.xml -r %COVERALLS_REPO_TOKEN%
deploy:
    provider: NuGet
    api_key: b11f3056-8100-4e18-bc0a-2dd2193f1e90
    on:
        branch: master
