//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitClassLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AcceptedDeviationAngleRadians {
            get {
                return ((string)(this["AcceptedDeviationAngleRadians"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03125")]
        public string AcceptedEqualityDeviationVolumeCubicInches {
            get {
                return ((string)(this["AcceptedEqualityDeviationVolumeCubicInches"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03125")]
        public string AcceptedEqualityDeviationDimensionInches {
            get {
                return ((string)(this["AcceptedEqualityDeviationDimensionInches"]));
            }
            set {
                this["AcceptedEqualityDeviationDimensionInches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.03125")]
        public string AcceptedEqualityDeviationAreaInchesSquared {
            get {
                return ((string)(this["AcceptedEqualityDeviationAreaInchesSquared"]));
            }
            set {
                this["AcceptedEqualityDeviationAreaInchesSquared"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AcceptedEqualityDeviationForceUnitPounds {
            get {
                return ((string)(this["AcceptedEqualityDeviationForceUnitPounds"]));
            }
            set {
                this["AcceptedEqualityDeviationForceUnitPounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string AcceptedEqualityDeviationStressPoundsPerSquareInch {
            get {
                return ((string)(this["AcceptedEqualityDeviationStressPoundsPerSquareInch"]));
            }
            set {
                this["AcceptedEqualityDeviationStressPoundsPerSquareInch"] = value;
            }
        }
    }
}
